name: Heroku Deploy

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'api-lmshub'
                  heroku_email: '22usyk08@gmail.com'
                  usedocker: true
